In [2]:
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import requests

In [2]:
user_agent_desktop = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36'

headers = { 'User-Agent': user_agent_desktop}

In [96]:
URL = "https://in.indeed.com/jobs?q=python&l="
data = requests.get(URL, headers= headers)

In [112]:
url = "https://in.indeed.com/jobs?q=python&start=40"
driver = webdriver.Chrome('chromedriver') 
driver.get(url) 
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")

In [109]:
cards = soup.find_all("div", attrs={"class": "jobsearch-SerpJobCard unifiedRow row result clickcard"})

In [ ]:
def move_page(number):
    url = f"https://in.indeed.com/jobs?q=python&start={number}0"
    driver = webdriver.Chrome('chromedriver') 
    driver.get(url) 
    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")
    cards = soup.find_all("li", attrs= {"class": "ais-InfiniteHits-item"})
    return cards

data= {"title": [],
       "company": [],
       "salary": [],
       "quick_resume": [],
       "date_from_now": [],
       "location": []}

for page in range(1, 5):
    for card in cards:
        spans = card.find_all("span")
        data['title'].append(spans[1].text if spans[1] else None)

        company = card.find("span", attrs= {"class": "companyName"})
        data['company'].append(company.text if company else None)

        salary = card.find("span", attrs= {"class": "salary-snippet"})
        data['salary'].append(salary.text if salary else None)

        as_application = card.find("span", attrs= {"class": "ialbl"})
        data['quick_resume'].append(as_application.text if as_application else None)

        date = card.find("span", attrs= {"class": "date"})
        data['date_from_now'].append(date.text if date else None)

        location = card.find("div", attrs= {"class":"companyLocation"})
        data['location'].append(location.text if location else None)

In [113]:
for card in cards:
    spans = card.find_all("span")
    print(spans[1].text)
#     print(card.find("span", attrs= {"class": "companyName"}).text)
#     for span in spans:
#         if not span.has_attr("class") and not span.has_attr("title"):
#             print(span.text)
#             break
    salary = card.find("span", attrs= {"class": "salary-snippet"})
    if salary: print(salary.text)
    else: print("Salary: NA")
        
    as_application = card.find("span", attrs= {"class": "ialbl"})
    if as_application: print(as_application.text)
    else: print("Resume: Original")
        
    date = card.find("span", attrs= {"class": "date"})
    if date: print(date.text)
    else: print("Date: NA")
        
    location = card.find("div", attrs= {"class":"companyLocation"})
    if location: print(location.text)
    else: print("Location: NA")
    
    
    
    
    print()

Inspire Networks Technology Solution Pvt Ltd
Salary: NA
Resume: Original
2 days ago
Location: NA




3.6


Salary: NA
Resume: Original
21 days ago
Location: NA


Kwiky Technologies
Salary: NA
Resume: Original
4 days ago
Location: NA


Feednet Solutions Private Limited
Salary: NA
Resume: Original
7 days ago
Location: NA

Lonavale, Maharashtra
Salary: NA
Resume: Original
21 days ago
Location: NA




4.0


Salary: NA
Resume: Original
18 days ago
Location: NA


Fermion Infotech Private Limited
Salary: NA
Resume: Original
1 day ago
Location: NA



Microsoft
Salary: NA
Resume: Original
Just posted
Location: NA



Sutherland
Salary: NA
Resume: Original
4 days ago
Location: NA

Remote
Salary: NA
Resume: Original
29 days ago
Location: NA

Noida, Uttar Pradesh
Salary: NA
Resume: Original
30+ days ago
Location: NA

Kochi, Kerala
Salary: NA
Resume: Original
11 days ago
Location: NA


Skyevo Educational Services Pvt Ltd
Salary: NA
Resume: Original
5 days ago
Location: NA


Citrusbug Technolabs
Salary: NA
Resume: Original
2 days ago
Location: NA



Radical Technologies
Salary: NA
Resume: Original
Just posted
Location: NA

In [112]:
data= {"title": [],
       "company": [],
       "salary": [],
       "quick_resume": [],
       "date_from_now": [],
       "location": []}

for card in cards:
    spans = card.find_all("span")
    data['title'].append(spans[1].text if spans[1] else None)
    
    company = card.find("span", attrs= {"class": "companyName"})
    data['company'].append(company.text if company else None)
    
    salary = card.find("span", attrs= {"class": "salary-snippet"})
    data['salary'].append(salary.text if salary else None)
        
    as_application = card.find("span", attrs= {"class": "ialbl"})
    data['quick_resume'].append(as_application.text if as_application else None)
        
    date = card.find("span", attrs= {"class": "date"})
    data['date_from_now'].append(date.text if date else None)
        
    location = card.find("div", attrs= {"class":"companyLocation"})
    data['location'].append(location.text if location else None)

In [3]:
import pandas as pd

In [113]:
pd.DataFrame(data)

,title,company,salary,quick_resume,date_from_now,location
0,Experienced Python Developer,Pixlie Web Solutions Pvt. Ltd.,"₹16,00,000 - ₹22,00,000 a year",Apply securely with Indeed Resume,4 days ago,"Bengaluru, Karnataka•Remote"
1,Python Developer Intern,Gateway Software Solutions,"₹5,000 a month",Apply securely with Indeed Resume,1 day ago,"Coimbatore, Tamil Nadu•Temporarily Remote"
2,Turbolab Technologies Private Limited,Turbolab Technologies Private Limited,"₹1,80,000 - ₹3,00,000 a year",None,27 days ago,"Ernakulam, Kerala•Remote"
3,Python Intern,Citrusbug Technolabs,"₹8,000 - ₹12,000 a month",None,5 days ago,"Ahmedabad, Gujarat"
4,Python- Backend Developer (Remote),Turbolab Technologies Private Limited,"₹15,000 - ₹50,000 a year",None,Just posted,"Ernakulam, Kerala•Remote"
5,Data Science (Python) part time job/internship...,Nitesh Kumar,"₹10,000 - ₹20,000 a month",None,8 days ago,"Delhi, Delhi•Remote"
6,Python Developer - Web Scraping (Remote),Turbolab Technologies Private Limited,"₹15,000 - ₹35,000 a year",None,4 days ago,"Ernakulam, Kerala•Remote"
7,Python Development Internship,Kwiky Technologies,"₹15,000 a month",None,3 days ago,"Guntur, Andhra Pradesh"
8,python developer -freelancer,Inspire Networks Technology Solution Pvt Ltd,₹100 - ₹400 a day,Apply securely with Indeed Resume,1 day ago,"Chennai, Tamil Nadu•Remote"
9,Python Developer Intern,Citrusbug Technolabs,"₹10,000 a month",Apply securely with Indeed Resume,5 days ago,"Ahmedabad, Gujarat•Remote"
10,vInnovate Technologies,vInnovate Technologies,None,None,20 days ago,"Lonavale, Maharashtra•Remote"
11,Python Developer,Skyevo Educational Services Pvt Ltd,"₹20,000 - ₹40,000 a month",Apply securely with Indeed Resume,4 days ago,"Gurgaon, Haryana•Temporarily Remote"
12,Python Developer -Freshers Product Company,LogixGRID Technologies Pvt. Ltd.,"₹12,000 a month",Apply securely with Indeed Resume,5 days ago,"Gurgaon, Haryana•Temporarily Remote"
13,Python Django E-commerce Website Developer,WebLead Technologies,"₹20,000 - ₹75,000 a month",Apply securely with Indeed Resume,4 days ago,"Bengaluru, Karnataka•Temporarily Remote"
14,Create:Next,Create:Next,₹499 - ₹998 an hour,Apply securely with Indeed Resume,30+ days ago,"Delhi, Delhi•Remote"

#

In [31]:
url = "https://www.coursera.org/courses?query=python"
data = BeautifulSoup(requests.get(url, headers= headers).content)

In [337]:
courses = data.find_all("li", attrs= {"class": "ais-InfiniteHits-item"})

In [338]:
data.find("div", attrs= {"class": "rc-ProductInfo"}).find("span", attrs= {"class": "difficulty"}).text

'Beginner'

In [30]:
url = "https://www.coursera.org/search?query=python&page=4&index=prod_all_products_term_optimization"

In [31]:
driver = webdriver.Chrome('chromedriver') 
driver.get(url)

In [32]:
html = driver.page_source

In [33]:
soup = BeautifulSoup(html, "html.parser")

In [34]:
courses = soup.find_all("li", attrs= {"class": "ais-InfiniteHits-item"})

In [43]:
kaka = courses[0].find("div", attrs= {"class": "card-content"})
kaka.find("h2").text

'Exploratory Data Analysis With Python and Pandas'

In [17]:
for course in courses:
    head = course.find("div", attrs= {"class": "card-content"})
    print(head.find("span", attrs= {"class": "partner-name"}).text)
    print(head.find("a", attrs= {"class": "color-primary-text"}).text)
    print(head.find("div", attrs= {"class":"_jen3vs"}).text)
    
    tail = course.find("div", attrs= {"class": "rc-ProductInfo"})
    print(tail.find("span", attrs= {"class":"ratings-text"}).text)
    print(tail.find("span", attrs= {"class":"ratings-count"}).text)
    print(tail.find("span", attrs= {"class":"enrollment-number"}).text)
    print(tail.find("span", attrs= {"class":"difficulty"}).text)
    print()

University of Colorado Boulder

AttributeError: 'NoneType' object has no attribute 'text'

In [44]:
data= {"university": [],
       "course": [],
       "type": [],
       "review": [],
       "votes": [],
       "studets": [],
       "difficulty": []}



for course in courses:
    tail = course.find("div", attrs= {"class": "rc-ProductInfo"})
    head = course.find("div", attrs= {"class": "card-content"})
    
    uni = head.find("span", attrs= {"class": "partner-name"})
    data['university'].append(uni.text if uni else None)
    
    course = head.find("h2", attrs= {"class": "color-primary-text"})
    data['course'].append(course.text if course else None)
    
    type_ = head.find("div", attrs= {"class":"_jen3vs"})
    data['type'].append(type_.text if type_ else None)
    
    # --
    
    
    review = tail.find("span", attrs= {"class":"ratings-text"})
    data['review'].append(review.text if review else None)
    
    votes = tail.find("span", attrs= {"class":"ratings-count"})
    data['votes'].append(votes.text if votes else None)
    
    students = tail.find("span", attrs= {"class":"enrollment-number"})
    data['studets'].append(students.text if students else None)
    
    difficulty = tail.find("span", attrs= {"class":"difficulty"})
    data['difficulty'].append(difficulty.text if difficulty else None)

In [86]:
data= {"university": [],
       "course": [],
       "type": [],
       "review": [],
       "votes": [],
       "studets": [],
       "difficulty": []}

def move_page(number):
    url = f"https://www.coursera.org/search?query=python&page={number}&index=prod_all_products_term_optimization"
    driver = webdriver.Chrome('chromedriver') 
    driver.get(url) 
    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")
    courses = soup.find_all("li", attrs= {"class": "ais-InfiniteHits-item"})
    return courses

for page in range(30, 50):
    courses = move_page(page)
    for course in courses:
        tail = course.find("div", attrs= {"class": "rc-ProductInfo"})
        head = course.find("div", attrs= {"class": "card-content"})

        uni = head.find("span", attrs= {"class": "partner-name"})
        data['university'].append(uni.text if uni else None)

        course = head.find("h2", attrs= {"class": "color-primary-text"})
        data['course'].append(course.text if course else None)

        type_ = head.find("div", attrs= {"class":"_jen3vs"})
        data['type'].append(type_.text if type_ else None)

        # --


        review = tail.find("span", attrs= {"class":"ratings-text"})
        data['review'].append(review.text if review else None)

        votes = tail.find("span", attrs= {"class":"ratings-count"})
        data['votes'].append(votes.text if votes else None)

        students = tail.find("span", attrs= {"class":"enrollment-number"})
        data['studets'].append(students.text if students else None)

        difficulty = tail.find("span", attrs= {"class":"difficulty"})
        data['difficulty'].append(difficulty.text if difficulty else None)

In [50]:
import pandas as pd

In [88]:
 pd.concat([df, pd.DataFrame(data)], ignore_index= True)

,university,course,type,review,votes,studets,difficulty
0,University of Colorado Boulder,Data Structures and Algorithms,SPECIALIZATION,None,None,None,Advanced
1,University of Michigan,Django for Everybody,SPECIALIZATION,4.7,"(1,334)",54k,Intermediate
2,DeepLearning.AI,Deep Learning,SPECIALIZATION,4.8,"(122,580)",1m,Intermediate
3,Infosec,Python for Cybersecurity,SPECIALIZATION,4.1,(7),None,Intermediate
4,IBM,Advanced Data Science with IBM,SPECIALIZATION,4.3,"(2,695)",110k,Advanced
...,...,...,...,...,...,...,...
265,IBM,Fundamentals of Scalable Data Science,COURSE,4.3,"(1,851)",56k,Beginner
266,DeepLearning.AI,Custom and Distributed Training with TensorFlow,COURSE,4.8,(154),5k,Intermediate
267,University of Washington,Computational Neuroscience,COURSE,4.6,(853),85k,Beginner
268,IBM,IBM AI Enterprise Workflow,SPECIALIZATION,4.3,(223),7.8k,Advanced
269,IBM,Bases de Inteligencia Artificial para Todos,PROFESSIONAL CERTIFICATE,4.7,(122),3.5k,Beginner

In [89]:
df = pd.concat([df, pd.DataFrame(data)], ignore_index= True)

In [90]:
df

,university,course,type,review,votes,studets,difficulty
0,University of Colorado Boulder,Data Structures and Algorithms,SPECIALIZATION,None,None,None,Advanced
1,University of Michigan,Django for Everybody,SPECIALIZATION,4.7,"(1,334)",54k,Intermediate
2,DeepLearning.AI,Deep Learning,SPECIALIZATION,4.8,"(122,580)",1m,Intermediate
3,Infosec,Python for Cybersecurity,SPECIALIZATION,4.1,(7),None,Intermediate
4,IBM,Advanced Data Science with IBM,SPECIALIZATION,4.3,"(2,695)",110k,Advanced
...,...,...,...,...,...,...,...
265,IBM,Fundamentals of Scalable Data Science,COURSE,4.3,"(1,851)",56k,Beginner
266,DeepLearning.AI,Custom and Distributed Training with TensorFlow,COURSE,4.8,(154),5k,Intermediate
267,University of Washington,Computational Neuroscience,COURSE,4.6,(853),85k,Beginner
268,IBM,IBM AI Enterprise Workflow,SPECIALIZATION,4.3,(223),7.8k,Advanced
269,IBM,Bases de Inteligencia Artificial para Todos,PROFESSIONAL CERTIFICATE,4.7,(122),3.5k,Beginner

In [73]:
import pickle

In [91]:
file = open("df", "wb")
pickle.dump(df, file)